# Generated by Django 4.2.7 on 2026-01-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('pasw', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('cmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=500)),
                ('cmp_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_complaint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_emp',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('firm_name', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=50)),
                ('emp_address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('pswd', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_emp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=10)),
                ('worker_id', models.CharField(max_length=10)),
                ('feedback_title', models.CharField(max_length=50)),
                ('feedback_description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tbl_feedback',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_insurence',
            fields=[
                ('insurence_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('myworker_id', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('insurence_type', models.CharField(max_length=100)),
                ('insurence_period', models.CharField(max_length=50)),
                ('insurence_rupee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currently_insured', models.CharField(max_length=10)),
                ('details', models.TextField()),
                ('nominee_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_insurence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_jobdetails',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('job_details', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_jobdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('u_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_login',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_noc',
            fields=[
                ('noc_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=10)),
                ('station_id', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=50)),
                ('crime', models.CharField(max_length=50)),
                ('crime_details', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'tbl_noc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_noccomplaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(max_length=10)),
                ('noc_id', models.CharField(max_length=10)),
                ('complaint', models.CharField(max_length=50)),
                ('complaint_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_noccomplaint',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_policestation',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_policestation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=150)),
                ('vacancy', models.CharField(max_length=50)),
                ('vacancy_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_vacancy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('worker_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('aadhar_number', models.CharField(max_length=50)),
                ('regis_date', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('languages_known', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('paswd', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_worker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_workerdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=10)),
                ('vacancy_id', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_workerdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_workershedule',
            fields=[
                ('shedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('worker_id', models.IntegerField()),
                ('job_details', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('time_from', models.CharField(max_length=50)),
                ('working_houres', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_workershedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='tbl_myworker',
            fields=[
                ('myworker_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('worker_id', models.IntegerField()),
                ('vacancy_id', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_myworker',
                'managed': True,
            },
        ),
    ]
