# Generated by Django 4.2.7 on 2026-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_workerdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='tbl_workerdetails',
            name='detail_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
