# Generated by Django 4.2.7 on 2026-01-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0002_remove_tbl_workerdetails_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_worker',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
