# Generated by Django 3.2 on 2026-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0003_tbl_worker_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_worker',
            options={},
        ),
        migrations.AlterField(
            model_name='tbl_worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workers/'),
        ),
        migrations.AlterField(
            model_name='tbl_worker',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tbl_worker',
            name='regis_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_worker',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
