# Generated by Django 3.2 on 2026-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Track', '0004_auto_20260221_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_vacancy',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
